<?php
/**
 * UsageBreakdownResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xactimate One API
 *
 * The Xactimate One API allows you to integrate your current services and applications directly with Xactimate One. It creates a seamless experience for your company as it manages claims with your internal software by sending and receiving data from the Xactimate One platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UsageBreakdownResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class UsageBreakdownResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UsageBreakdownResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'actual_cash_value' => 'double',
        'actual_cash_value_overage' => 'double',
        'difference' => 'double',
        'difference_overage' => 'double',
        'replacement_cost' => 'double',
        'replacement_cost_overage' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'actual_cash_value' => 'double',
        'actual_cash_value_overage' => 'double',
        'difference' => 'double',
        'difference_overage' => 'double',
        'replacement_cost' => 'double',
        'replacement_cost_overage' => 'double'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'actual_cash_value' => 'actualCashValue',
        'actual_cash_value_overage' => 'actualCashValueOverage',
        'difference' => 'difference',
        'difference_overage' => 'differenceOverage',
        'replacement_cost' => 'replacementCost',
        'replacement_cost_overage' => 'replacementCostOverage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'actual_cash_value' => 'setActualCashValue',
        'actual_cash_value_overage' => 'setActualCashValueOverage',
        'difference' => 'setDifference',
        'difference_overage' => 'setDifferenceOverage',
        'replacement_cost' => 'setReplacementCost',
        'replacement_cost_overage' => 'setReplacementCostOverage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'actual_cash_value' => 'getActualCashValue',
        'actual_cash_value_overage' => 'getActualCashValueOverage',
        'difference' => 'getDifference',
        'difference_overage' => 'getDifferenceOverage',
        'replacement_cost' => 'getReplacementCost',
        'replacement_cost_overage' => 'getReplacementCostOverage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['actual_cash_value'] = $data['actual_cash_value'] ?? null;
        $this->container['actual_cash_value_overage'] = $data['actual_cash_value_overage'] ?? null;
        $this->container['difference'] = $data['difference'] ?? null;
        $this->container['difference_overage'] = $data['difference_overage'] ?? null;
        $this->container['replacement_cost'] = $data['replacement_cost'] ?? null;
        $this->container['replacement_cost_overage'] = $data['replacement_cost_overage'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['actual_cash_value'] === null) {
            $invalidProperties[] = "'actual_cash_value' can't be null";
        }
        if ($this->container['actual_cash_value_overage'] === null) {
            $invalidProperties[] = "'actual_cash_value_overage' can't be null";
        }
        if ($this->container['difference'] === null) {
            $invalidProperties[] = "'difference' can't be null";
        }
        if ($this->container['difference_overage'] === null) {
            $invalidProperties[] = "'difference_overage' can't be null";
        }
        if ($this->container['replacement_cost'] === null) {
            $invalidProperties[] = "'replacement_cost' can't be null";
        }
        if ($this->container['replacement_cost_overage'] === null) {
            $invalidProperties[] = "'replacement_cost_overage' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets actual_cash_value
     *
     * @return double
     */
    public function getActualCashValue()
    {
        return $this->container['actual_cash_value'];
    }

    /**
     * Sets actual_cash_value
     *
     * @param double $actual_cash_value The actual cash value.
     *
     * @return self
     */
    public function setActualCashValue($actual_cash_value)
    {
        $this->container['actual_cash_value'] = $actual_cash_value;

        return $this;
    }

    /**
     * Gets actual_cash_value_overage
     *
     * @return double
     */
    public function getActualCashValueOverage()
    {
        return $this->container['actual_cash_value_overage'];
    }

    /**
     * Sets actual_cash_value_overage
     *
     * @param double $actual_cash_value_overage The difference of the actual cash value and the deductible.
     *
     * @return self
     */
    public function setActualCashValueOverage($actual_cash_value_overage)
    {
        $this->container['actual_cash_value_overage'] = $actual_cash_value_overage;

        return $this;
    }

    /**
     * Gets difference
     *
     * @return double
     */
    public function getDifference()
    {
        return $this->container['difference'];
    }

    /**
     * Sets difference
     *
     * @param double $difference The difference of the replacement and actual cost values.
     *
     * @return self
     */
    public function setDifference($difference)
    {
        $this->container['difference'] = $difference;

        return $this;
    }

    /**
     * Gets difference_overage
     *
     * @return double
     */
    public function getDifferenceOverage()
    {
        return $this->container['difference_overage'];
    }

    /**
     * Sets difference_overage
     *
     * @param double $difference_overage The difference of the replacement and actual cost value overages.
     *
     * @return self
     */
    public function setDifferenceOverage($difference_overage)
    {
        $this->container['difference_overage'] = $difference_overage;

        return $this;
    }

    /**
     * Gets replacement_cost
     *
     * @return double
     */
    public function getReplacementCost()
    {
        return $this->container['replacement_cost'];
    }

    /**
     * Sets replacement_cost
     *
     * @param double $replacement_cost The replacement cost value.
     *
     * @return self
     */
    public function setReplacementCost($replacement_cost)
    {
        $this->container['replacement_cost'] = $replacement_cost;

        return $this;
    }

    /**
     * Gets replacement_cost_overage
     *
     * @return double
     */
    public function getReplacementCostOverage()
    {
        return $this->container['replacement_cost_overage'];
    }

    /**
     * Sets replacement_cost_overage
     *
     * @param double $replacement_cost_overage The differnce of the replacement cost value and the deductible.
     *
     * @return self
     */
    public function setReplacementCostOverage($replacement_cost_overage)
    {
        $this->container['replacement_cost_overage'] = $replacement_cost_overage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


