<?php
/**
 * LossUpdateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Xactimate One API
 *
 * The Xactimate One API allows you to integrate your current services and applications directly with Xactimate One. It creates a seamless experience for your company as it manages claims with your internal software by sending and receiving data from the Xactimate One platform.
 *
 * OpenAPI spec version: null
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LossUpdateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description LossUpdateRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LossUpdateRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LossUpdateRequest"
     */
    public function testLossUpdateRequest()
    {
    }

    /**
     * Test attribute "first_notice_of_loss"
     */
    public function testPropertyFirstNoticeOfLoss()
    {
    }

    /**
     * Test attribute "loss_date"
     */
    public function testPropertyLossDate()
    {
    }

    /**
     * Test attribute "loss_description"
     */
    public function testPropertyLossDescription()
    {
    }

    /**
     * Test attribute "peril"
     */
    public function testPropertyPeril()
    {
    }

    /**
     * Test attribute "potential_subrogation"
     */
    public function testPropertyPotentialSubrogation()
    {
    }
}
