<?php
/**
 * PropertyClaimPolicyInfoCoveragesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Xactimate One Customer Api
 *
 * The client claims API provides an integration point for Xactimate clients to create and manage insurance claims within the Xactimate One system.
 *
 * OpenAPI spec version: 0.1.1
 * Contact: contact@xactware.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PropertyClaimPolicyInfoCoveragesTest Class Doc Comment
 *
 * @category    Class
 * @description An insurance coverage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PropertyClaimPolicyInfoCoveragesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PropertyClaimPolicyInfoCoverages"
     */
    public function testPropertyClaimPolicyInfoCoverages()
    {
    }

    /**
     * Test attribute "linked_coverage_id"
     */
    public function testPropertyLinkedCoverageId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "policy_limit"
     */
    public function testPropertyPolicyLimit()
    {
    }

    /**
     * Test attribute "deductible"
     */
    public function testPropertyDeductible()
    {
    }

    /**
     * Test attribute "apply_to"
     */
    public function testPropertyApplyTo()
    {
    }

    /**
     * Test attribute "itv"
     */
    public function testPropertyItv()
    {
    }

    /**
     * Test attribute "reserve"
     */
    public function testPropertyReserve()
    {
    }

    /**
     * Test attribute "sublimits"
     */
    public function testPropertySublimits()
    {
    }

    /**
     * Test attribute "additional_coverages"
     */
    public function testPropertyAdditionalCoverages()
    {
    }
}
